openapi: 3.0.0
servers: []
info:
  description: The API used by Klimb.
  version: "1.0.0"
  title: Klimb API
  contact:
    email: bradleytenuta@outlook.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Game
    description: Calls in regard to the game itself.
paths:
  /generate-map:
    get:
      tags:
        - Game
      summary: Generates a map that the game will be played on.
      operationId: generateMap
      description: |
        By passing in the appropriate options, a map will be
        generated.
      parameters:
        - in: query
          name: seed
          description: A map is generated based on the seed provided.
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
      responses:
        '200':
          description: Map generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneratedMap'
        '400':
          description: Invalid input provided
components:
  schemas:
    GeneratedMap:
      type: object
      required:
        - seed
        - nodes
      properties:
        seed:
          type: integer
          format: int64
          minimum: 0
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
    Node:
      type: object
      required:
        - nodeType
      properties:
        nodeType:
          $ref: '#/components/schemas/NodeType'
    NodeType:
      type: string
      enum:
        - single